void stuff_char _P((int, int, struct ppp_out *));
void add_fcs _P((struct ppp_out *, int));
int check_fcs _P((u_char *, int));
int sifdown _P((int));
int sifup  _P((int));
void ppp_recv_config  _P((int, int, u_int32_t, int, int));
void ppp_set_xaccm _P((int, u_int32_t *));
void ppp_send_config  _P((int, int, u_int32_t, int, int));
void sifvjcomp  _P((int, int, int, int));
void doframe _P((struct ttys *));
void ppp_input _P((struct ttys *, u_char *, int));
int ppp_encap _P((char *, struct mbuf *, int, int, int));
void output _P((int, u_char *, int));
void die _P((int));
void ppp_init _P((struct ttys *));
void ppp_start _P((int));
int sifaddr  _P((int, int, int, int));
int cifaddr  _P((int, int, int));
int sifdefaultroute  _P((int, int));
int cifdefaultroute  _P((int, int));
int cifproxyarp  _P((int, u_long));
int sifproxyarp  _P((int, u_long));
int run_program _P((char *, char **, int));
int ccp_test _P((int, u_char *, int, int));
void ccp_flags_set _P((int, int, int));
int ccp_fatal_error _P((int));
void ppp_ccp _P((struct ttys *, u_char *, int, int));
void ppp_ccp_closed _P((struct ttys *));
